spring:
  datasource:
    url: jdbc:mysql://localhost/audiobook
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB